### ISSUE TITLE
Cleanups

### ISSUE THREAD

**Issue by xsawyerx** [xsawyerx/pakket#22]
- [x] Default output directory should be `./output/`.
- [x] Absolute symlink paths should not be supported. There, decision made. :)
- [x] Add versioning to the package filename.
- [x] Include metadata in bundle file.
- [x] Move all checks for paths as [Types::Path::Tiny](https://metacpan.org/pod/Types::Path::Tiny)'s `Path` (unless needs absolute path, in which case `AbsPath`).
- [x] Correct [logging](https://github.com/xsawyerx/pkt/blob/master/lib/Pkt/Builder.pm#L85) so that `-v` has output.
- [x] Add coercion to `Path::Tiny` attributes.
- [x] Use `Path::Tiny::chmod`.
- [x] Send logger to all classes.

**Comment by xsawyerx** [comment]
Most of these were fixed and merged upstream. The rest will probably wait for more. Addition items can be added here if anyone finds it comfortable.
