### ISSUE TITLE
Installer improvements

### ISSUE THREAD

**Issue by xsawyerx** [xsawyerx/pakket#23]
The installer unpacks the bundle file and copies it to the installation directory. The installation directory could have a default (coming from a config file) or it could be specified on the spot (coming from the command line).

The installer should be able to create a runner that fits what it installed (such as if it installed it locally using `--local` or something).

The installer should eventually be a separate package that can be installed separately. We could generate it from the main project and make it available as a package in distribution packaging (RPM, Deb, etc.) or as fatpacked that can be downloaded and used.

Functionality:
- [x] Install everything into a single directory (regression)
- [x] Install dependencies recursively
- [x] Support multiple sources (HTTP/FTP/Git/etc.)
- [x] Provide package name to pick automatically from repository
- [x] Support multiple library directories
- [x] Uninstall/remove option
- [x] Storing the metadata

**Comment by xsawyerx** [comment]
Last two items are now missing.

**Comment by xsawyerx** [comment]
All done!
